name: "Swiftly Compiler"

on:
  push:
    branches:
      - "**"
    paths:
      - 'src/**'
      - 'plugin_files/**'
      - 'protobufs/**'
      - 'alliedmodders/**'
      - 'vendor/**'
      - '.github/workflows/**'
  pull_request:
  workflow_dispatch:

jobs:
  versioning:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Packages
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y curl jq

      - name: Generate version
        uses: reecetech/version-increment@2024.4.4
        id: version
        with:
          release_branch: master
          increment: major
          use_api: true

  extensions_build:
    name: Extension Build
    needs: versioning
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        extension:
          [
            mysql-extension,
            console-filter,
            addons-extension,
            http-extension,
            ip-extension,
            utils-extension,
            sdktools-extension,
            websocket-extension,
          ]
        include:
          - os: ubuntu-latest
            container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
      - name: Checkout Extension
        uses: actions/checkout@v4
        with:
          repository: swiftly-solution/${{ matrix.extension }}
          path: ${{ matrix.extension }}
          submodules: recursive

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Version
        shell: bash
        run: echo "VERSION=${{needs.versioning.outputs.version}}" >> $GITHUB_ENV

      - name: Build - Linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: ${{ matrix.extension }}
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libreadline-dev libboost-all-dev
          bash ./setup.sh

      - name: Build - Windows
        if: matrix.os == 'windows-latest'
        working-directory: ${{ matrix.extension }}
        run: |
          ./setup.ps1

      - name: IP EXT - Linux
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.extension == 'ip-extension' }}
        working-directory: ${{ matrix.extension }}
        shell: bash
        run: |
          wget https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb -O build/package/addons/swiftly/data/GeoLite2-City.mmdb
          wget https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb -O build/package/addons/swiftly/data/GeoLite2-ASN.mmdb

      - name: IP EXT - Windows
        if: ${{ matrix.os == 'windows-latest' && matrix.extension == 'ip-extension' }}
        working-directory: ${{ matrix.extension }}
        run: |
          Set-Location build/package/addons/swiftly

          Invoke-WebRequest https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb -OutFile data/GeoLite2-City.mmdb
          Invoke-WebRequest https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb -OutFile data/GeoLite2-ASN.mmdb

          Set-Location ../../../..

      - name: Upload Artifacts Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.extension}}.Extension.Linux
          path: ${{ github.workspace }}/${{ matrix.extension }}/build/package

      - name: Upload Artifacts Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.extension}}.Extension.Windows
          path: ${{ github.workspace }}/${{ matrix.extension }}/build/package

  build_managed:
    name: Build Managed C#
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: swiftly

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Clone Extensions
        working-directory: swiftly
        shell: bash
        run: |
          extensions=("mysql-extension" "console-filter" "addons-extension" "http-extension" "ip-extension" "utils-extension" "sdktools-extension" "websocket-extension")

          for repo in "${extensions[@]}"; do
            git clone https://github.com/swiftly-solution/$repo.git
            if [ -d $repo/managed ]; then
              mkdir -p src/managed/API/Extensions/$repo
              cp -rf $repo/managed/* src/managed/API/Extensions/$repo/
            fi
          done

      - uses: actions/upload-artifact@v4
        with:
          name: swiftlys2-managed-files-${{ needs.versioning.outputs.version }}
          path: ${{ github.workspace }}/swiftly/src/managed

      - name: Restore CSProj
        working-directory: swiftly
        shell: bash
        run: dotnet restore src/managed/SwiftlyS2.csproj

      - name: Build Project
        working-directory: swiftly
        shell: bash
        run: |
          dotnet publish -c Release /p:Version=${{needs.versioning.outputs.version}} src/managed

          dotnet pack -c Release /p:Version=${{needs.versioning.outputs.version}} src/managed

      - uses: actions/upload-artifact@v4
        with:
          name: swiftlys2-managed-${{ needs.versioning.outputs.version }}
          path: ${{ github.workspace }}/swiftly/src/managed/bin/Release

  build_docs:
    name: Build Documentation
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: swiftly

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clone Extensions
        working-directory: swiftly
        shell: bash
        run: |
          extensions=("mysql-extension" "console-filter" "addons-extension" "http-extension" "ip-extension" "utils-extension" "sdktools-extension" "websocket-extension")

          for repo in "${extensions[@]}"; do
            git clone https://github.com/swiftly-solution/$repo.git
            if [ -d $repo/documentation ]; then
              cp -rf $repo/documentation/* generators/documentation
            fi
            if [ -d $repo/sdkdocumentation ]; then
              cp -rf $repo/sdkdocumentation/* generators/sdkdocumentation
            fi
          done

      - name: Build Documentation
        working-directory: swiftly
        shell: bash
        run: |
          cd generators/docsgen
          node index.mjs


      - name: Upload Pages
        uses: actions/upload-artifact@v4
        with:
          name: swiftlys2-documentation
          path: ${{ github.workspace }}/swiftly/generators/docsgen/*.json

  build:
    name: Build
    needs: versioning
    runs-on: ${{ matrix.os }}
    env:
      MMSOURCE20: ${{ github.workspace }}/swiftly/alliedmodders/metamod
      HL2SDKCS2: ${{ github.workspace }}/swiftly/alliedmodders/hl2sdk
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: swiftly
          submodules: recursive

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Setup Version
        shell: bash
        run: echo "SWIFTLY_VERSION=${{needs.versioning.outputs.version}}" >> $GITHUB_ENV

      - name: Build - Linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: swiftly
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libreadline-dev libboost-all-dev unzip patchelf
          bash ./setup.sh
          patchelf --set-rpath '$ORIGIN' build/package/addons/swiftly/bin/linuxsteamrt64/swiftly.so

          echo "[Builder] Setting up default plugins"
          cp -r build/package build/package2
          cd build/package/addons/swiftly
          wget https://github.com/swiftly-solution/admins/releases/latest/download/Swiftly.Plugin.Admins.zip
          unzip Swiftly.Plugin.Admins.zip
          wget https://github.com/swiftly-solution/admins_basecomms/releases/latest/download/Swiftly.Plugin.Admins.BaseComms.zip
          unzip Swiftly.Plugin.Admins.BaseComms.zip
          wget https://github.com/swiftly-solution/admins_basebans/releases/latest/download/Swiftly.Plugin.Admins.BaseBans.zip
          unzip Swiftly.Plugin.Admins.BaseBans.zip
          wget https://github.com/swiftly-solution/admins_commands/releases/latest/download/Swiftly.Plugin.Admins.BaseCommands.zip
          unzip Swiftly.Plugin.Admins.BaseCommands.zip
          wget https://github.com/swiftly-solution/map-chooser/releases/latest/download/Swiftly.Plugin.Map-Chooser.zip
          unzip Swiftly.Plugin.Map-Chooser.zip 
          wget https://github.com/swiftly-solution/cookies/releases/latest/download/cookies.zip
          unzip cookies.zip

          rm -rf Swiftly.Plugin.Admins.zip
          rm -rf Swiftly.Plugin.Admins.BaseComms.zip
          rm -rf Swiftly.Plugin.Admins.BaseBans.zip
          rm -rf Swiftly.Plugin.Admins.BaseCommands.zip
          rm -rf Swiftly.Plugin.Map-Chooser.zip
          rm -rf cookies.zip

          cd ../../../..
          echo "[Builder] Finished setting up default plugins"

      - name: Build - Windows
        if: matrix.os == 'windows-latest'
        working-directory: swiftly
        run: |
          ./setup.ps1

          Set-Location build/package/addons/swiftly

          Invoke-WebRequest https://github.com/swiftly-solution/admins/releases/latest/download/Swiftly.Plugin.Admins.zip -OutFile Swiftly.Plugin.Admins.zip
          Expand-Archive Swiftly.Plugin.Admins.zip -DestinationPath .
          Invoke-WebRequest https://github.com/swiftly-solution/admins_basecomms/releases/latest/download/Swiftly.Plugin.Admins.BaseComms.zip -OutFile Swiftly.Plugin.Admins.BaseComms.zip
          Expand-Archive Swiftly.Plugin.Admins.BaseComms.zip -DestinationPath .
          Invoke-WebRequest https://github.com/swiftly-solution/admins_basebans/releases/latest/download/Swiftly.Plugin.Admins.BaseBans.zip -OutFile Swiftly.Plugin.Admins.BaseBans.zip
          Expand-Archive Swiftly.Plugin.Admins.BaseBans.zip -DestinationPath .
          Invoke-WebRequest https://github.com/swiftly-solution/admins_commands/releases/latest/download/Swiftly.Plugin.Admins.BaseCommands.zip -OutFile Swiftly.Plugin.Admins.BaseCommands.zip
          Expand-Archive Swiftly.Plugin.Admins.BaseCommands.zip -DestinationPath .
          Invoke-WebRequest https://github.com/swiftly-solution/map-chooser/releases/latest/download/Swiftly.Plugin.Map-Chooser.zip -OutFile Swiftly.Plugin.Map-Chooser.zip
          Expand-Archive Swiftly.Plugin.Map-Chooser.zip -DestinationPath .
          Invoke-WebRequest https://github.com/swiftly-solution/cookies/releases/latest/download/cookies.zip -OutFile cookies.zip
          Expand-Archive cookies.zip -DestinationPath .

          Remove-Item -Force Swiftly.Plugin.Admins.zip
          Remove-Item -Force Swiftly.Plugin.Admins.BaseComms.zip
          Remove-Item -Force Swiftly.Plugin.Admins.BaseBans.zip
          Remove-Item -Force Swiftly.Plugin.Admins.BaseCommands.zip
          Remove-Item -Force Swiftly.Plugin.Map-Chooser.zip
          Remove-Item -Force cookies.zip

          Set-Location ../../../..

      - name: Upload Artifacts Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Swiftly.Core.Linux
          path: ${{ github.workspace }}/swiftly/build/package

      - name: Upload Artifacts Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Swiftly.Core.Windows
          path: ${{ github.workspace }}/swiftly/build/package

  packer:
    needs: ["build", "extensions_build", "build_managed", "build_docs"]
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
      - uses: actions/download-artifact@v4
        id: download-artifacts
        with:
          path: build

      - name: Prepare ZIP Files
        run: |
          sudo apt install unzip -y;

          find build -type d -name "*Extension.Linux" -exec cp -r {}/addons build/Swiftly.Core.Linux \;
          find build -type d -name "*Extension.Windows" -exec cp -r {}/addons build/Swiftly.Core.Windows \;

          find build -type d -name "swiftlys2-managed-*" -exec sh -c 'cp "$1"/net8.0/publish/* build/Swiftly.Core.Linux/addons/swiftly/bin/managed' _ {} \;
          find build -type d -name "swiftlys2-managed-*" -exec sh -c 'cp "$1"/net8.0/publish/* build/Swiftly.Core.Windows/addons/swiftly/bin/managed' _ {} \;

          mkdir -p build/Swiftly.Core.Linux/addons/swiftly/bin/managed/dotnet
          cd build/Swiftly.Core.Linux/addons/swiftly/bin/managed/dotnet

          wget https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.19/aspnetcore-runtime-8.0.19-linux-x64.tar.gz
          tar zxvf aspnetcore-runtime-8.0.19-linux-x64.tar.gz
          rm aspnetcore-runtime-8.0.19-linux-x64.tar.gz

          cd ../../../../../../..

          mkdir -p build/Swiftly.Core.Windows/addons/swiftly/bin/managed/dotnet
          cd build/Swiftly.Core.Windows/addons/swiftly/bin/managed/dotnet

          wget https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/8.0.19/aspnetcore-runtime-8.0.19-win-x64.zip
          unzip aspnetcore-runtime-8.0.19-win-x64.zip
          rm aspnetcore-runtime-8.0.19-win-x64.zip

          cd ../../../../../../..

          echo "PATH_ARTIFACTS=$(pwd)" >> $GITHUB_ENV

      - name: Upload Artifacts Linux
        uses: actions/upload-artifact@v4
        with:
          name: Swiftly.Plugin.Linux
          path: ${{env.PATH_ARTIFACTS}}/build/Swiftly.Core.Linux

      - name: Upload Artifacts Windows
        uses: actions/upload-artifact@v4
        with:
          name: Swiftly.Plugin.Windows
          path: ${{env.PATH_ARTIFACTS}}/build/Swiftly.Core.Windows

  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    permissions:
      contents: write
    needs: ["packer", "versioning"]
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
      - uses: actions/download-artifact@v4
        id: download-artifacts
        with:
          name: Swiftly.Plugin.Linux
          path: buildlin

      - uses: actions/download-artifact@v4
        id: download-artifacts-2
        with:
          name: Swiftly.Plugin.Windows
          path: buildwin

      - uses: actions/download-artifact@v4
        id: download-managed
        with:
          name: swiftlys2-managed-${{ needs.versioning.outputs.version }}
          path: build

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Nuget Publish
        run: |
          dotnet nuget push build/SwiftlyS2.${{ needs.versioning.outputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.versioning.outputs.version }}
          make_latest: "true"
          body: "Changelog for this version can be found inside [CHANGELOG.md](https://github.com/swiftly-solution/swiftly/blob/master/CHANGELOG.md)"
          files: |
            buildlin/Swiftly.Plugin.Linux.zip
            buildwin/Swiftly.Plugin.Windows.zip
